# Investigate flaky `parallel/test-http-readable-data-event`

URL: https://ci.nodejs.org/job/node-test-commit/12345/
Source: https://github.com/nodejs/node/pull/12345/
Commit: [5f7e056] fs: do not crash when using a closed fs event watcher
Date: 2018-05-27 13:05:05 +0800
Author: Someone <foo@bar.com>

#### [ppcle-ubuntu1404](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=ppcle-ubuntu1404/16673/console)

<details>
<summary>See failures</summary>

```
not ok 749 parallel/test-http-readable-data-event
  ---
  duration_ms: 0.420
  severity: fail
  stack: |-
    assert.js:80
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: 'Hello World!Hello again later!' strictEqual 'Hello World!'
        at IncomingMessage.res.on.common.mustCall (/home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/test/parallel/test-http-readable-data-event.js:43:14)
        at IncomingMessage.<anonymous> (/home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/test/common/index.js:467:15)
        at IncomingMessage.emit (events.js:182:13)
        at IncomingMessage.Readable.read (_stream_readable.js:489:10)
        at IncomingMessage.res.on.common.mustCall (/home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/test/parallel/test-http-readable-data-event.js:36:20)
        at IncomingMessage.<anonymous> (/home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/test/common/index.js:467:15)
        at IncomingMessage.emit (events.js:182:13)
        at emitReadable_ (_stream_readable.js:537:12)
        at process._tickCallback (internal/process/next_tick.js:174:19)
  ...

```
</details>
